GET http://localhost:3000/players/ 
### 

GET http://localhost:3000/players/12/ 
### 

POST http://localhost:3000/players/ 
Content-Type: Application/json 
{ 
    "playerName": "Sachin Tendulkar", 
    "jerseyNumber": 900, 
    "role": "All-Rounder" 
} 
### 

PUT http://localhost:3000/players/17 
Content-Type: Application/json 
{ 
    "playerName": "Hardick Pandeya", 
    "jerseyNumber": 9999, 
    "role": "Batsman" 
} 
### 

DELETE http://localhost:3000/players/12/ 
###